Ddcnls 3833
hmrc/business-customer-frontend pull request #86
Opened 2018-11-09 10:51 UTC by ashwinirudrappa

2018-11-13 15:16 UTC, Gaur4vGaur requested changes

2018-11-13 15:16 UTC, Gaur4vGaur commented on app/controllers/nonUKReg/BusinessRegController.scala
> +        println(formWithErrors)
Get rid of println

2018-11-13 15:16 UTC, Gaur4vGaur commented on app/utils/BusinessCustomerConstants.scala
> +  val issuingCountryRegex = "(?!^GB$)^[A-Z]{2}$"
Please follow naming conventions to declare constants

2018-11-13 15:16 UTC, Gaur4vGaur commented on test/forms/BusinessRegistrationFormsSpec.scala
> +  "Businessegistration form" should {
Use 'must' for consistency

2018-11-13 15:16 UTC, Gaur4vGaur commented on test/forms/BusinessRegistrationFormsSpec.scala
> +  "Businessegistration form" should {
please use must throughout

2018-11-13 15:16 UTC, Gaur4vGaur commented on test/forms/BusinessRegistrationFormsSpec.scala
> +    // Error message needs to be updated
is this comment still valid?

2018-11-13 15:16 UTC, Gaur4vGaur commented on test/forms/BusinessRegistrationFormsSpec.scala
> +
would it be worth calling fail, to catch the situation when form does not throw any validation?

2018-11-13 15:16 UTC, Gaur4vGaur commented on test/forms/BusinessVerificationFormsSpec.scala
> +  "Soletrader form " should {
Please be consistent and use 'must' throughout

2018-11-13 17:16 UTC, ashwinirudrappa commented on test/forms/BusinessRegistrationFormsSpec.scala
> +    // Error message needs to be updated
Fixed

2018-11-13 17:16 UTC, ashwinirudrappa commented on test/forms/BusinessVerificationFormsSpec.scala
> +  "Soletrader form " should {
Fixed

2018-11-13 17:23 UTC, ashwinirudrappa commented on app/utils/BusinessCustomerConstants.scala
> +  val issuingCountryRegex = "(?!^GB$)^[A-Z]{2}$"
Fixed

2018-11-13 17:24 UTC, ashwinirudrappa commented on test/forms/BusinessRegistrationFormsSpec.scala
> +
Fixed

2018-11-13 17:27 UTC, ashwinirudrappa commented on test/forms/BusinessRegistrationFormsSpec.scala
> +  "Businessegistration form" should {
Fixed

2018-11-16 10:33 UTC, Gaur4vGaur requested changes

2018-11-16 10:33 UTC, Gaur4vGaur commented on test/forms/BusinessVerificationFormsSpec.scala
> +  "limitedPartnershipForm" should {
Use 'must' for consistency

2018-11-16 10:33 UTC, Gaur4vGaur commented on test/forms/BusinessRegistrationFormsSpec.scala
> +  "Businessegistration form" must {
typo!

2018-11-16 11:10 UTC, ashwinirudrappa commented on test/forms/BusinessRegistrationFormsSpec.scala
> +  "Businessegistration form" must {
Fixed it, so sorry

2018-11-16 11:48 UTC, Gaur4vGaur approved these changes

2019-04-24 12:07 UTC, closed without merging